### ISSUE TITLE
Problème de compilation depuis la Mise à Jour 1.1.0

### ISSUE THREAD

**Issue by BOBILLEChristophe** [pierremolinaro/acan-esp32#6]
Bonjour Pierre,

Petit problème à la compilation depuis mon passage à la 1.1.0. Du coup, retour à la version précédente qui compile bien.

Mac OSX 10.14.6 - IDE Arduino 1.8.19

Bravo pour le travail réalisé avec ces biblio et merci par avance pour la réponse.

Christophe

/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp: In member function 'void ACAN_ESP32::setGPIOPins(gpio_num_t, gpio_num_t)':
/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp:52:32: error: 'TWAI_TX_IDX' was not declared in this scope
   pinMatrixOutAttach (inTXPin, TWAI_TX_IDX, false, false) ;
                                ^
/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp:55:31: error: 'TWAI_RX_IDX' was not declared in this scope
   pinMatrixInAttach (inRXPin, TWAI_RX_IDX, false) ;
                               ^
/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp: In member function 'uint32_t ACAN_ESP32::begin(const ACAN_ESP32_Settings&, const ACAN_ESP32_Filter&)':
/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp:153:25: error: 'PERIPH_TWAI_MODULE' was not declared in this scope
   periph_module_enable (PERIPH_TWAI_MODULE) ;
                         ^
/Users/christophe/Documents/Arduino/libraries/ACAN_ESP32/src/ACAN_ESP32.cpp:206:19: error: 'ETS_TWAI_INTR_SOURCE' was not declared in this scope
   esp_intr_alloc (ETS_TWAI_INTR_SOURCE, 0, isr, this, & mInterruptHandler) ;

**Comment by pierremolinaro** [comment]
Bonjour Christophe,

Il faut sans doute mettre à jour via le Board Manager la gestionnaire des cartes ESP32 : j'utilise la dernière, la 2.0.5.

Quelle version utilises-tu ?

Et merci pour tes encouragements !

Amicalement,

Pierre

**Comment by JohnGENZ** [comment]
Hi
I think 2.0.5 refers to the Arduino Core.  It is good to know that ACAN 1.1.0 works with V2.0.5. of the Core.

I use ACAN 1.1.0 with V2.0.3 and it works perfectly.  I had great difficulty updating to V2.0.5 of the Core.

V2.0.5 of the Arduino core uses ESP-IDF v4.4.2.  Something in my system (not ACAN) seems not to work with this version of the Espressif IDE.

Kind Regards, John

**Comment by pierremolinaro** [comment]
Hello,

To be precise, I use:
	- MacOS 12.6
	- Arduino IDE 2.0.0
	- ESP32 from Espressif Systems 2.0.5
	- ACAN_ESP32 1.1.0
	
I have just checked ACAN_ESP32 1.1.0 compiles with ESP32 from Espressif Systems 2.0.4 and ESP32 from Espressif Systems 2.0.0.

Best regards,

Pierre
