### ISSUE TITLE
Compile Error: esp_private/periph_ctrl.h & periph_interrput_t

### ISSUE THREAD

**Issue by Mmaarrooo** [pierremolinaro/acan-esp32#21]
Hello,

While compiling it gets me two errors:
.pio/libdeps/esp32-gateway/ACAN_ESP32/src/ACAN_ESP32_TWAI_base_address.h:63:16: error: 'periph_interrput_t' does not name a type; did you mean 'periph_module_t'?

.pio/libdeps/esp32-gateway/ACAN_ESP32/src/ACAN_ESP32.cpp:9:10: fatal error: esp_private/periph_ctrl.h: No such file or directory

Build infos:
PlatformIo
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-gateway.html
PLATFORM: Espressif 32 (6.10.0) > OLIMEX ESP32-GATEWAY
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

Solution:

Line 63, ACAN_ESP32_TWAI_base_address.h -->   static const periph_interrput_t twaiInterruptSource = ETS_TWAI_INTR_SOURCE ; Change to:   static const int twaiInterruptSource = ETS_TWAI_INTR_SOURCE ;

ACAN_ESP32.cpp
add include of: #include <driver/periph_ctrl.h> // Include this header for periph_module_enable
Delete include of: #include <esp_private/periph_ctrl.h> // For ESP32 board manager

**Comment by pierremolinaro** [comment]
Hello Mmaarrooo,

I have published a new release (3.0.3) that compiles with ESP32 2.0.17 board manager. 
Unfortunatly, Espressif is rather annoying because it regularly changes headers.

Best Regards,

Pierre
